# Generated by Django 3.1.5 on 2021-01-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='choice',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
