# Generated by Django 3.1.5 on 2021-01-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_to_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
